<?php


namespace app\index\controller;


use app\model\Banner;
use app\model\Cate;
use think\db\exception\DataNotFoundException;
use think\db\exception\ModelNotFoundException;
use think\facade\View;

class Index extends Base
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        return view($this->tpl);
    }

    public function search()
    {
        $keyword = input('keyword');

        View::assign([
            'keyword' => $keyword
        ]);
        return view($this->tpl);
    }
}