<?php


namespace app\api\controller;


use app\BaseController;

class Base extends BaseController
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $data = request()->param();
        if (!isset($data['api_key']) || $data['api_key'] != config('site.api_key'))
           return json(['code' => 1, 'message' => 'Api密钥为空/密钥错误'])->send();
    }
}